---
# The autoscaler-metrics instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: metricscollector, eventgenerator
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-metrics"
  labels:
    skiff-role-name: "autoscaler-metrics"
spec:
  podManagementPolicy: "Parallel"
  replicas: 0
  serviceName: "autoscaler-metrics-set"
  template:
    metadata:
      name: "autoscaler-metrics"
      labels:
        skiff-role-name: "autoscaler-metrics"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_ASACTORS_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASACTORS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-client-key"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-key"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-server-key"
              name: "secrets"
        - name: "AUTOSCALER_CF_SKIP_SSL_VALIDATION"
          value: "true"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "AUTOSCALER_DEFAULT_BREACH_DURATION_SECS"
          value: "300"
        - name: "AUTOSCALER_DEFAULT_STAT_WINDOW_SECS"
          value: "300"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_APP_METRIC_CHANNEL_SIZE"
          value: "1000"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_APP_MONITOR_CHANNEL_SIZE"
          value: "200"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_EXECUTE_INTERVAL"
          value: "40s"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_METRIC_POLLER_COUNT"
          value: "20"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_POLICY_POLLER_INTERVAL"
          value: "40s"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_SAVE_INTERVAL"
          value: "5s"
        - name: "AUTOSCALER_EVENT_GENERATOR_CIRCUIT_BREAKER_BACK_OFF_INITIAL_INTERVAL"
          value: "5m"
        - name: "AUTOSCALER_EVENT_GENERATOR_CIRCUIT_BREAKER_BACK_OFF_MAX_INTERVAL"
          value: "120m"
        - name: "AUTOSCALER_EVENT_GENERATOR_CIRCUIT_BREAKER_CONSECUTIVE_FAILURE_COUNT"
          value: "3"
        - name: "AUTOSCALER_EVENT_GENERATOR_EVALUATOR_EVALUATION_MANAGER_EXECUTE_INTERVAL"
          value: "40s"
        - name: "AUTOSCALER_EVENT_GENERATOR_EVALUATOR_EVALUATOR_COUNT"
          value: "20"
        - name: "AUTOSCALER_EVENT_GENERATOR_EVALUATOR_TRIGGER_ARRAY_CHANNEL_SIZE"
          value: "200"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECTOR_COLLECT_INTERVAL"
          value: "30s"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECTOR_REFRESH_INTERVAL"
          value: "60s"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECTOR_SAVE_INTERVAL"
          value: "30s"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECT_METHOD"
          value: "streaming"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_UAA_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-uaa-client-secret"
              name: "secrets"
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-autoscaler-metrics:60486d38fc6a7416e7f6400f2d434bd77dd0ae33"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-metrics"
        ports:
        - containerPort: 7103
          name: "metrics"
          protocol: "TCP"
        - containerPort: 7105
          name: "eventgen"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "4000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-metrics-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "metrics"
      port: 7103
      protocol: "TCP"
      targetPort: 0
    - name: "eventgen"
      port: 7105
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "autoscaler-metrics"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-metrics"
  spec:
    ports:
    - name: "metrics"
      port: 7103
      protocol: "TCP"
      targetPort: 7103
    - name: "eventgen"
      port: 7105
      protocol: "TCP"
      targetPort: 7105
    selector:
      skiff-role-name: "autoscaler-metrics"
kind: "List"
