---
# The cc-worker instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - cloud_controller_worker: Cloud Controller worker processes background tasks
#   submitted via the.
#
# Also: loggregator_agent
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "cc-worker"
  labels:
    skiff-role-name: "cc-worker"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  serviceName: "cc-worker-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "cc-worker"
      name: "cc-worker"
    spec:
      containers:
      - env:
        - name: "ALLOW_APP_SSH_ACCESS"
          value: "true"
        - name: "BLOBSTORE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "blobstore-password"
              name: "secrets"
        - name: "BROKER_CLIENT_TIMEOUT_SECONDS"
          value: "70"
        - name: "CC_DB_CURRENT_KEY_LABEL"
          value: ""
        - name: "CC_DB_ENCRYPTION_KEYS"
          valueFrom:
            secretKeyRef:
              key: "cc-db-encryption-keys"
              name: "secrets"
        - name: "CC_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "cc-server-crt"
              name: "secrets"
        - name: "CC_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "cc-server-key"
              name: "secrets"
        - name: "CDN_URI"
          value: ""
        - name: "DB_ENCRYPTION_KEY"
          valueFrom:
            secretKeyRef:
              key: "db-encryption-key"
              name: "secrets"
        - name: "DEFAULT_APP_DISK_IN_MB"
          value: "1024"
        - name: "DEFAULT_APP_MEMORY"
          value: "1024"
        - name: "DEFAULT_APP_SSH_ACCESS"
          value: "true"
        - name: "DEFAULT_STACK"
          value: "opensuse42"
        - name: "DISABLE_CUSTOM_BUILDPACKS"
          value: "false"
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_API_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "internal-api-password"
              name: "secrets"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MAX_APP_DISK_IN_MB"
          value: "2048"
        - name: "MAX_HEALTH_CHECK_TIMEOUT"
          value: "180"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_CCDB_ROLE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-ccdb-role-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "STAGING_TIMEOUT"
          value: "900"
        - name: "STAGING_UPLOAD_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "staging-upload-password"
              name: "secrets"
        - name: "SUSE_STACK"
          value: "opensuse42"
        - name: "SUSE_STACK_DESCRIPTION"
          value: "openSUSE-based filesystem"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_CC_ROUTING_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cc-routing-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_CC_SERVICE_DASHBOARDS_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cc-service-dashboards-client-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        - name: "USE_DIEGO_PRIVILEGED_CONTAINERS"
          value: "false"
        - name: "USE_STAGER_PRIVILEGED_CONTAINERS"
          value: "false"
        image: "splatform/scf-cc-worker:ec24325ddd620a887bb998ff96cc450e68380d9d"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "cc-worker"
        ports: ~
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "753Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
