---
# The log-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: loggregator_trafficcontroller, loggregator_agent, reverse_log_proxy
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "log-api"
  labels:
    skiff-role-name: "log-api"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  serviceName: "log-api-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "log-api"
      name: "log-api"
    spec:
      containers:
      - env:
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secrets"
        - name: "SYSLOG_RLP_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-key"
              name: "secrets"
        - name: "TRAFFICCONTROLLER_CERT"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-cert"
              name: "secrets"
        - name: "TRAFFICCONTROLLER_KEY"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-key"
              name: "secrets"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_DOPPLER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-doppler-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-log-api:d4471e916abb0f0a02f5f818d5e00468962a74ab"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "log-api"
        ports:
        - containerPort: 8081
          name: "dropsonde"
          protocol: "TCP"
        - containerPort: 8082
          name: "rlp"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8081/set-cookie"
        resources:
          requests:
            memory: "250Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api"
  spec:
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 8081
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 8082
    selector:
      skiff-role-name: "log-api"
kind: "List"
