---
# The nfs-broker instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: loggregator_agent, nfsbroker
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "nfs-broker"
  labels:
    skiff-role-name: "nfs-broker"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: 1
  serviceName: "nfs-broker-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "nfs-broker"
      name: "nfs-broker"
    spec:
      containers:
      - env:
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_PERSI_NFS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-persi-nfs-password"
              name: "secrets"
        - name: "PERSI_NFS_ALLOWED_OPTIONS"
          value: "uid,gid,auto_cache,username,password"
        - name: "PERSI_NFS_BROKER_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "persi-nfs-broker-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-nfs-broker:047a8d8932848b3be4826f9b059c102a47666e43"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "nfs-broker"
        ports:
        - containerPort: 8999
          name: "nfsbroker"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "63Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "nfs-broker-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "nfsbroker"
      port: 8999
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "nfs-broker"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "nfs-broker"
  spec:
    ports:
    - name: "nfsbroker"
      port: 8999
      protocol: "TCP"
      targetPort: 8999
    selector:
      skiff-role-name: "nfs-broker"
kind: "List"
