apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    db: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    db: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        db: redis
    spec:
      containers:
      - name: redis
        image: redis:4
        args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "1"]
        tty: true
        stdin: true
        ports:
        - containerPort: 6379
