---
# The autoscaler-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - route_registrar: Used for registering routes
#
# Also: apiserver, servicebroker
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-api"
  labels:
    skiff-role-name: "autoscaler-api"
spec:
  podManagementPolicy: "Parallel"
  replicas: 0
  serviceName: "autoscaler-api-set"
  template:
    metadata:
      name: "autoscaler-api"
      labels:
        skiff-role-name: "autoscaler-api"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_API_SERVER_DB_CONFIG_IDLE_TIMEOUT"
          value: "100"
        - name: "AUTOSCALER_API_SERVER_DB_CONFIG_MAX_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_API_SERVER_DB_CONFIG_MIN_CONNECTIONS"
          value: "0"
        - name: "AUTOSCALER_API_SERVER_INFO_BUILD"
          value: "beta"
        - name: "AUTOSCALER_API_SERVER_INFO_DESCRIPTION"
          value: "autoscaler"
        - name: "AUTOSCALER_API_SERVER_INFO_NAME"
          value: "autoscalerapiserver"
        - name: "AUTOSCALER_API_SERVER_INFO_SUPPORT_URL"
          value: ""
        - name: "AUTOSCALER_ASACTORS_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASACTORS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-client-key"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-client-key"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_PUBLIC_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-public-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_PUBLIC_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-public-server-key"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-server-key"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-key"
              name: "secrets"
        - name: "AUTOSCALER_CF_SKIP_SSL_VALIDATION"
          value: "true"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "AUTOSCALER_SERVICE_BROKER_DB_CONFIG_IDLE_TIMEOUT"
          value: "1000"
        - name: "AUTOSCALER_SERVICE_BROKER_DB_CONFIG_MAX_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_SERVICE_BROKER_DB_CONFIG_MIN_CONNECTIONS"
          value: "0"
        - name: "AUTOSCALER_SERVICE_BROKER_HTTP_REQUEST_TIMEOUT"
          value: "5000"
        - name: "AUTOSCALER_SERVICE_BROKER_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-service-broker-password"
              name: "secrets"
        - name: "AUTOSCALER_SERVICE_OFFERING_ENABLED"
          value: "false"
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        image: "splatform/scf-autoscaler-api:5889d323f5bbb17627d7ca9a87eb53688a6df4c2"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-api"
        ports:
        - containerPort: 7100
          name: "api"
          protocol: "TCP"
        - containerPort: 7106
          name: "api-public"
          protocol: "TCP"
        - containerPort: 7107
          name: "broker"
          protocol: "TCP"
        - containerPort: 7101
          name: "broker-public"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "256Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "api"
      port: 7100
      protocol: "TCP"
      targetPort: 0
    - name: "api-public"
      port: 7106
      protocol: "TCP"
      targetPort: 0
    - name: "broker"
      port: 7107
      protocol: "TCP"
      targetPort: 0
    - name: "broker-public"
      port: 7101
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "autoscaler-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-api"
  spec:
    ports:
    - name: "api"
      port: 7100
      protocol: "TCP"
      targetPort: 7100
    - name: "api-public"
      port: 7106
      protocol: "TCP"
      targetPort: 7106
    - name: "broker"
      port: 7107
      protocol: "TCP"
      targetPort: 7107
    - name: "broker-public"
      port: 7101
      protocol: "TCP"
      targetPort: 7101
    selector:
      skiff-role-name: "autoscaler-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-api-public"
  spec:
    externalIPs:
    - "192.168.77.77"
    ports:
    - name: "api-public"
      port: 7106
      protocol: "TCP"
      targetPort: 7106
    - name: "broker-public"
      port: 7101
      protocol: "TCP"
      targetPort: 7101
    selector:
      skiff-role-name: "autoscaler-api"
kind: "List"
