---
# The autoscaler-actors instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: scalingengine, scheduler, pruner
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-actors"
  labels:
    skiff-role-name: "autoscaler-actors"
spec:
  podManagementPolicy: "Parallel"
  replicas: 0
  serviceName: "autoscaler-actors-set"
  template:
    metadata:
      name: "autoscaler-actors"
      labels:
        skiff-role-name: "autoscaler-actors"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_ASACTORS_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASACTORS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-client-key"
              name: "secrets"
        - name: "AUTOSCALER_ASACTORS_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASACTORS_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asactors-server-key"
              name: "secrets"
        - name: "AUTOSCALER_CF_SKIP_SSL_VALIDATION"
          value: "true"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "AUTOSCALER_DEFAULT_COOLDOWN_SECS"
          value: "300"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_LOCK_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_LOCK_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_LOCK_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_PRUNER_APP_METRICS_DB_CUTOFF_DAYS"
          value: "30"
        - name: "AUTOSCALER_PRUNER_APP_METRICS_DB_REFRESH_INTERVAL"
          value: "24h"
        - name: "AUTOSCALER_PRUNER_ENABLE_DB_LOCK"
          value: "true"
        - name: "AUTOSCALER_PRUNER_INSTANCE_METRICS_DB_CUTOFF_DAYS"
          value: "30"
        - name: "AUTOSCALER_PRUNER_INSTANCE_METRICS_DB_REFRESH_INTERVAL"
          value: "24h"
        - name: "AUTOSCALER_PRUNER_LOCK_RETRY_INTERVAL"
          value: "10s"
        - name: "AUTOSCALER_PRUNER_LOCK_TTL"
          value: "15s"
        - name: "AUTOSCALER_PRUNER_SCALING_ENGINE_DB_CUTOFF_DAYS"
          value: "30"
        - name: "AUTOSCALER_PRUNER_SCALING_ENGINE_DB_FRESH_INTERVAL"
          value: "24h"
        - name: "AUTOSCALER_SCALING_ENGINE_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_SCALING_ENGINE_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_SCALING_ENGINE_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_SCALING_ENGINE_HEALTH_EMIT_INTERVAL"
          value: "15s"
        - name: "AUTOSCALER_SCALING_ENGINE_LOCK_SIZE"
          value: "32"
        - name: "AUTOSCALER_SCALING_ENGINE_SYNCHRONIZER_ACTIVE_SCHEDULE_SYNC_INTERVAL"
          value: "600s"
        - name: "AUTOSCALER_SCHEDULER_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_SCHEDULER_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_SCHEDULER_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_SCHEDULER_JOB_RESCHEDULE_INTERVAL_MILISECOND"
          value: "100"
        - name: "AUTOSCALER_SCHEDULER_JOB_RESCHEDULE_MAXCOUNT"
          value: "6"
        - name: "AUTOSCALER_SCHEDULER_NOTIFICATION_RESCHEDULE_MAXCOUNT"
          value: "3"
        - name: "AUTOSCALER_UAA_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-uaa-client-secret"
              name: "secrets"
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-autoscaler-actors:26f13e0d47b1d286c8e8f81fa0c5071d8b4eae4b"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-actors"
        ports:
        - containerPort: 7104
          name: "scaling-engine"
          protocol: "TCP"
        - containerPort: 7102
          name: "scheduler"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-actors-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "scaling-engine"
      port: 7104
      protocol: "TCP"
      targetPort: 0
    - name: "scheduler"
      port: 7102
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "autoscaler-actors"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-actors"
  spec:
    ports:
    - name: "scaling-engine"
      port: 7104
      protocol: "TCP"
      targetPort: 7104
    - name: "scheduler"
      port: 7102
      protocol: "TCP"
      targetPort: 7102
    selector:
      skiff-role-name: "autoscaler-actors"
kind: "List"
