---
# The cc-uploader instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: tps, cc_uploader, loggregator_agent
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "cc-uploader"
  labels:
    skiff-role-name: "cc-uploader"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  serviceName: "cc-uploader-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "cc-uploader"
      name: "cc-uploader"
    spec:
      containers:
      - env:
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets"
        - name: "BBS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-key"
              name: "secrets"
        - name: "CC_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "cc-server-crt"
              name: "secrets"
        - name: "CC_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "cc-server-key"
              name: "secrets"
        - name: "CC_UPLOADER_CRT"
          valueFrom:
            secretKeyRef:
              key: "cc-uploader-crt"
              name: "secrets"
        - name: "CC_UPLOADER_KEY"
          valueFrom:
            secretKeyRef:
              key: "cc-uploader-key"
              name: "secrets"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "TPS_CC_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "tps-cc-client-crt"
              name: "secrets"
        - name: "TPS_CC_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "tps-cc-client-key"
              name: "secrets"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-cc-uploader:eadf296ff34a802f3ee1bc25852f5f0053de28fb"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "cc-uploader"
        ports:
        - containerPort: 9091
          name: "cc-up-listen"
          protocol: "TCP"
        - containerPort: 17018
          name: "cc-up-dbg"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "129Mi"
            cpu: "4000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cc-uploader-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "cc-up-listen"
      port: 9091
      protocol: "TCP"
      targetPort: 0
    - name: "cc-up-dbg"
      port: 17018
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "cc-uploader"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cc-uploader"
  spec:
    ports:
    - name: "cc-up-listen"
      port: 9091
      protocol: "TCP"
      targetPort: 9091
    - name: "cc-up-dbg"
      port: 17018
      protocol: "TCP"
      targetPort: 17018
    selector:
      skiff-role-name: "cc-uploader"
kind: "List"
