---
# The routing-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: loggregator_agent, routing-api
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "routing-api"
  labels:
    skiff-role-name: "routing-api"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: 1
  serviceName: "routing-api-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "routing-api"
      name: "routing-api"
    spec:
      containers:
      - env:
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets"
        - name: "DIEGO_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-key"
              name: "secrets"
        - name: "DNS_HEALTH_CHECK_HOST"
          value: "127.0.0.1"
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SIZING_TCP_ROUTER_PORTS_TCP_ROUTE_MAX"
          value: "20008"
        - name: "KUBE_SIZING_TCP_ROUTER_PORTS_TCP_ROUTE_MIN"
          value: "20000"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_ROUTING_API_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-routing-api-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-routing-api:9fca330ffff05d3f39f91701e493fbc4735eecc4"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "routing-api"
        ports:
        - containerPort: 3000
          name: "routing-api"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/usr/bin/env"
            - "FISSILE_ACTIVE_PASSIVE_PROBE=head -c0 </dev/tcp/${HOSTNAME}/3000"
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "114Mi"
            cpu: "4000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "routing-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "routing-api"
      port: 3000
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "routing-api"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "routing-api"
  spec:
    ports:
    - name: "routing-api"
      port: 3000
      protocol: "TCP"
      targetPort: 3000
    selector:
      skiff-role-name: "routing-api"
      skiff-role-active: "true"
kind: "List"
