---
# The syslog-scheduler instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: scheduler, loggregator_agent
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "syslog-scheduler"
  labels:
    skiff-role-name: "syslog-scheduler"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  serviceName: "syslog-scheduler-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "syslog-scheduler"
      name: "syslog-scheduler"
    spec:
      containers:
      - env:
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "SYSLOG_SCHED_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-sched-cert"
              name: "secrets"
        - name: "SYSLOG_SCHED_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-sched-key"
              name: "secrets"
        image: "splatform/scf-syslog-scheduler:fa50edf11128cba5ac31ca90f857dd530c7a9905"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "syslog-scheduler"
        ports:
        - containerPort: 8080
          name: "sched-health"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8080/health"
        resources:
          requests:
            memory: "69Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "syslog-scheduler-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "sched-health"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "syslog-scheduler"
kind: "List"
