---
# The autoscaler-postgres instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - postgres: The Postgres server provides a single instance Postgres database
#   that can be used with the Cloud Controller or the UAA. It does not provide
#   highly-available configuration.
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-postgres"
  labels:
    skiff-role-name: "autoscaler-postgres"
spec:
  podManagementPolicy: "Parallel"
  replicas: 0
  serviceName: "autoscaler-postgres-set"
  template:
    metadata:
      name: "autoscaler-postgres"
      labels:
        skiff-role-name: "autoscaler-postgres"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_DATABASE_MAX_CONNECTIONS"
          value: "1000"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        image: "splatform/scf-autoscaler-postgres:ab34d3cbdfcc10818cae6bd47acbbe98c88873ab"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-postgres"
        ports:
        - containerPort: 5432
          name: "postgres"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts:
        - mountPath: "/var/vcap/store"
          name: "postgres-data"
          readOnly: false
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
  volumeClaimTemplates:
  - metadata:
      name: "postgres-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: "persistent"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "100G"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "autoscaler-postgres"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres"
  spec:
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 5432
    selector:
      skiff-role-name: "autoscaler-postgres"
kind: "List"
