---
# The diego-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   SCF patches for upstream bugs
#
# Also: bbs, cfdot, loggregator_agent, locket
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "diego-api"
  labels:
    skiff-role-name: "diego-api"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: 1
  serviceName: "diego-api-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "diego-api"
      name: "diego-api"
    spec:
      containers:
      - env:
        - name: "BBS_ACTIVE_KEY_PASSPHRASE"
          valueFrom:
            secretKeyRef:
              key: "bbs-active-key-passphrase"
              name: "secrets"
        - name: "BBS_AUCTIONEER_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert"
              name: "secrets"
        - name: "BBS_AUCTIONEER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-key"
              name: "secrets"
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets"
        - name: "BBS_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-key"
              name: "secrets"
        - name: "BBS_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt"
              name: "secrets"
        - name: "BBS_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-key"
              name: "secrets"
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets"
        - name: "DIEGO_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-key"
              name: "secrets"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_DIEGO_LOCKET_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-locket-password"
              name: "secrets"
        - name: "MYSQL_DIEGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-diego-api:6a6d2d09ce1565ae61775df3730bcc5a7a091ac4"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-api"
        ports:
        - containerPort: 8889
          name: "cell-bbs-api"
          protocol: "TCP"
        - containerPort: 17017
          name: "cell-bbs-dbg"
          protocol: "TCP"
        - containerPort: 8891
          name: "locket"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/usr/bin/env"
            - "FISSILE_ACTIVE_PASSIVE_PROBE=/var/vcap/jobs/global-properties/bin/readiness/diego-api"
            - "/opt/fissile/readiness-probe.sh"
            - "head -c0 </dev/tcp/${HOSTNAME}/8891"
        resources:
          requests:
            memory: "310Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: 0
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: 0
    - name: "locket"
      port: 8891
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "diego-api"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api"
  spec:
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: 8889
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: 17017
    - name: "locket"
      port: 8891
      protocol: "TCP"
      targetPort: 8891
    selector:
      skiff-role-name: "diego-api"
      skiff-role-active: "true"
kind: "List"
