---
# The diego-access instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: ssh_proxy, loggregator_agent, file_server
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "diego-access"
  labels:
    skiff-role-name: "diego-access"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  serviceName: "diego-access-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "diego-access"
      name: "diego-access"
    spec:
      containers:
      - env:
        - name: "APP_SSH_KEY"
          valueFrom:
            secretKeyRef:
              key: "app-ssh-key"
              name: "secrets"
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets"
        - name: "BBS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-key"
              name: "secrets"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_DIEGO_SSH_PROXY_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-diego-ssh-proxy-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-diego-access:2c57a4d0d3db68ab97adb61e6a196bf4abf8d1de"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-access"
        ports:
        - containerPort: 2222
          name: "diego-ssh"
          protocol: "TCP"
        - containerPort: 8080
          name: "diego-files"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8080/v1/static/file_server/bin/file-server"
        resources:
          requests:
            memory: "123Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-access-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "diego-ssh"
      port: 2222
      protocol: "TCP"
      targetPort: 0
    - name: "diego-files"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "diego-access"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-access"
  spec:
    ports:
    - name: "diego-ssh"
      port: 2222
      protocol: "TCP"
      targetPort: 2222
    - name: "diego-files"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      skiff-role-name: "diego-access"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-access-public"
  spec:
    externalIPs:
    - "192.168.77.77"
    ports:
    - name: "diego-ssh"
      port: 2222
      protocol: "TCP"
      targetPort: 2222
    selector:
      skiff-role-name: "diego-access"
kind: "List"
