---
# The tcp-router instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - wait-for-uaa: Wait for UAA to be ready before starting any jobs
#
# Also: tcp_router, loggregator_agent
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "tcp-router"
  labels:
    skiff-role-name: "tcp-router"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  serviceName: "tcp-router-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "tcp-router"
      name: "tcp-router"
    spec:
      containers:
      - env:
        - name: "DNS_HEALTH_CHECK_HOST"
          value: "127.0.0.1"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_TCP_ROUTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-tcp-router-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-tcp-router:945db49117a99a73d2ca8fa47a4c31778e696b28"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "tcp-router"
        ports:
        - containerPort: 8080
          name: "healthcheck"
          protocol: "TCP"
        - containerPort: 20000
          name: "tcp-route-20000"
          protocol: "TCP"
        - containerPort: 20001
          name: "tcp-route-20001"
          protocol: "TCP"
        - containerPort: 20002
          name: "tcp-route-20002"
          protocol: "TCP"
        - containerPort: 20003
          name: "tcp-route-20003"
          protocol: "TCP"
        - containerPort: 20004
          name: "tcp-route-20004"
          protocol: "TCP"
        - containerPort: 20005
          name: "tcp-route-20005"
          protocol: "TCP"
        - containerPort: 20006
          name: "tcp-route-20006"
          protocol: "TCP"
        - containerPort: 20007
          name: "tcp-route-20007"
          protocol: "TCP"
        - containerPort: 20008
          name: "tcp-route-20008"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8080/health"
        resources:
          requests:
            memory: "99Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "tcp-router-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "healthcheck"
      port: 2341
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-0"
      port: 20000
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-1"
      port: 20001
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-2"
      port: 20002
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-3"
      port: 20003
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-4"
      port: 20004
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-5"
      port: 20005
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-6"
      port: 20006
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-7"
      port: 20007
      protocol: "TCP"
      targetPort: 0
    - name: "tcp-route-8"
      port: 20008
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "tcp-router"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "tcp-router"
  spec:
    ports:
    - name: "healthcheck"
      port: 2341
      protocol: "TCP"
      targetPort: 8080
    - name: "tcp-route-0"
      port: 20000
      protocol: "TCP"
      targetPort: 20000
    - name: "tcp-route-1"
      port: 20001
      protocol: "TCP"
      targetPort: 20001
    - name: "tcp-route-2"
      port: 20002
      protocol: "TCP"
      targetPort: 20002
    - name: "tcp-route-3"
      port: 20003
      protocol: "TCP"
      targetPort: 20003
    - name: "tcp-route-4"
      port: 20004
      protocol: "TCP"
      targetPort: 20004
    - name: "tcp-route-5"
      port: 20005
      protocol: "TCP"
      targetPort: 20005
    - name: "tcp-route-6"
      port: 20006
      protocol: "TCP"
      targetPort: 20006
    - name: "tcp-route-7"
      port: 20007
      protocol: "TCP"
      targetPort: 20007
    - name: "tcp-route-8"
      port: 20008
      protocol: "TCP"
      targetPort: 20008
    selector:
      skiff-role-name: "tcp-router"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "tcp-router-public"
  spec:
    externalIPs:
    - "192.168.77.77"
    ports:
    - name: "tcp-route-0"
      port: 20000
      protocol: "TCP"
      targetPort: 20000
    - name: "tcp-route-1"
      port: 20001
      protocol: "TCP"
      targetPort: 20001
    - name: "tcp-route-2"
      port: 20002
      protocol: "TCP"
      targetPort: 20002
    - name: "tcp-route-3"
      port: 20003
      protocol: "TCP"
      targetPort: 20003
    - name: "tcp-route-4"
      port: 20004
      protocol: "TCP"
      targetPort: 20004
    - name: "tcp-route-5"
      port: 20005
      protocol: "TCP"
      targetPort: 20005
    - name: "tcp-route-6"
      port: 20006
      protocol: "TCP"
      targetPort: 20006
    - name: "tcp-route-7"
      port: 20007
      protocol: "TCP"
      targetPort: 20007
    - name: "tcp-route-8"
      port: 20008
      protocol: "TCP"
      targetPort: 20008
    selector:
      skiff-role-name: "tcp-router"
kind: "List"
