---
# The smoke-tests instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - smoke_tests: The smoke tests errand can be configured to run quick set of
#   tests against a specific Cloud Foundry API endpoint to determine is basic
#   push-application functionality works. Consider running the acceptance tests
#   errand for a more extensive set of tests.
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "smoke-tests"
  labels:
    skiff-role-name: "smoke-tests"
spec:
  containers:
  - env:
    - name: "CLUSTER_ADMIN_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "cluster-admin-password"
          name: "secrets"
    - name: "DOMAIN"
      value: "cf-dev.io"
    - name: "GARDEN_ROOTFS_DRIVER"
      value: "btrfs"
    - name: "INTERNAL_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert"
          name: "secrets"
    - name: "KUBERNETES_NAMESPACE"
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: "MONIT_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "monit-password"
          name: "secrets"
    - name: "SCF_LOG_PORT"
      value: "514"
    - name: "SCF_LOG_PROTOCOL"
      value: "tcp"
    - name: "UAA_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "uaa-ca-cert"
          name: "secrets"
    image: "splatform/scf-smoke-tests:771f9bafdfb0e6b75e57c217cebeba8c570f5fcf"
    lifecycle:
      preStop:
        exec:
          command:
          - "/opt/fissile/pre-stop.sh"
    livenessProbe: ~
    name: "smoke-tests"
    ports: ~
    readinessProbe: ~
    resources:
      requests: {}
      limits: {}
    securityContext: ~
    volumeMounts: ~
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "registry-credentials"
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 600
  volumes: ~
